; PlatformIO Project Configuration File for VAPA ESP32 Sensor Node
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4.2
    adafruit/Adafruit BusIO @ ^1.16.1
    Wire
